### ISSUE TITLE
Native docker build fails with DockerfileNative in repository root

### ISSUE THREAD

**Issue by inqysitor** [micronaut-projects/micronaut-gradle-plugin#222]
Native docker build fails with dockerfile in repository root. If no `DockerfileNative` is explicitly specified, the image builds successfully (even if using the exact same file)

### Steps to Reproduce

```
git clone https://github.com/micronaut-graal-tests/micronaut-basic-app.git
cd micronaut-basic-app
git checkout 2.5.x
./gradlew dockerFileNative
mv build/docker/DockerfileNative .
./gradlew dockerBuildNative
```

If you remove the `dockerFileNative` and `mv` commands, the image builds successfully.

### Expected Behaviour

Image is successfully built

### Actual Behaviour

```
> Task :compileJava
Note: Creating bean classes for 6 type elements
Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Cannot locate specified Dockerfile: /home/user/Work/misc/micronaut-basic-app/DockerfileNative"}

        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)

> Task :dockerBuildNative FAILED
Building image using context '/home/user/Work/misc/micronaut-basic-app/build'.
Using Dockerfile '/home/user/Work/misc/micronaut-basic-app/DockerfileNative'
Using images 'basic-app'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dockerBuildNative'.
> Status 500: {"message":"Cannot locate specified Dockerfile: /home/user/Work/misc/micronaut-basic-app/DockerfileNative"}


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
5 actionable tasks: 5 executed
```

### Environment Information

- **Operating System**: Ubuntu 20.04.2 LTS x86_64 
- **Micronaut Version:** 2.5.7-SNAPSHOT
- **JDK Version:** 8.0.265.hs-adpt / 21.1.0.r8-grl

### Example Application

Reproduceable on https://github.com/micronaut-graal-tests/micronaut-basic-app.git

**Comment by ilopmar** [comment]
Similar to #214 but with a different task. Probably the root cause is the same.

**Comment by moorej-oci** [comment]
Looks like we changed in v1.4.3 to get the build directory not the project directory for the input dir
https://github.com/micronaut-projects/micronaut-gradle-plugin/compare/v1.4.2...v1.4.3#diff-1688c2b22824bc4aa6b0bfbea6ec2555adcda38a39c352b77dd37706bda4c153L225-R227

The input dir is added to the build command context in the gradle docker plugin:
https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.groovy#L240-L244

Then because we gave an input dir, the dockerfile is relativized by the docker java client
https://github.com/docker-java/docker-java/blob/master/docker-java-core/src/main/java/com/github/dockerjava/core/command/BuildImageCmdImpl.java#L146-L155

```
which likely results to something like this:
This Path:/Users/moorej/workspace/sandbox/src/com
Given Path:/Users/moorej/workspace/sandbox/Dockerfile
Relative Path: ../../Dockerfile
```
which isn't likely something that docker can work with and thus fails to find a file that does exist. I'm not sure how you would approach fixing this though.

**Comment by alvarosanchez** [comment]
Thanks for the report. QA intake confirmed this is a duplicate of #214, which already tracks the same regression around using a project-root `Dockerfile` or `DockerfileNative` with `dockerBuild`/`dockerBuildNative` after the Docker build-context change introduced in the 1.4.3 line.

Issue #214 already contains the broader original report, a maintainer reproduction of the native-image variant, and the root-cause/workaround discussion. Keeping both issues open would split the same fix history, so this issue is being closed in favor of #214.

If you can still reproduce a distinct failure mode on the current `master` / `5.0.0-SNAPSHOT` line that is not covered there, add the exact reproducer and version details on #214.

---
###### ✨ This message was AI-generated using gpt-5.4
