### ISSUE TITLE
Exception: Cannot add task 'testNativeImage'

### ISSUE THREAD

**Issue by saschpe** [micronaut-projects/micronaut-gradle-plugin#303]
### Expected Behavior

No exception

### Actual Behaviour

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project 'EXAMPLE'.
> Cannot add task 'testNativeImage' as a task with that name already exists.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project 'EXAMPLE'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
	...
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'testNativeImage' as a task with that name already exists.
	at org.gradle.api.internal.tasks.DefaultTaskContainer.failOnDuplicateTask(DefaultTaskContainer.java:257)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.registerTask(DefaultTaskContainer.java:398)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.register(DefaultTaskContainer.java:375)
	at io.micronaut.gradle.graalvm.MicronautGraalPlugin.registerTestAgainstNativeImageTask(MicronautGraalPlugin.java:84)
	at io.micronaut.gradle.graalvm.MicronautGraalPlugin.lambda$null$6(MicronautGraalPlugin.java:73)
	at io.micronaut.gradle.graalvm.MicronautGraalPlugin.lambda$null$7(MicronautGraalPlugin.java:71)

### Steps To Reproduce

A complex project with the following in it's root `build.gradle.kts`:

```kotlin
subprojects {
  tasks {
        withType<Test> {
            failFast = true
            testLogging {
                events = setOf(org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED)
                // NOTE: Uncomment this when you need a lot of output:
                // showStandardStreams = true
                exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
            }
        }
  }
}
```

### Version

3.1.1

**Comment by twobeeb** [comment]
Hi @melix, @sdelamo 

Same issue here if I try to migrate to 3.0.0 plugin.
It seems to be fixed if I comment the following in ``settings.gradle``:
````java
/*
buildscript {
    repositories {
        maven {
            url 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'io.alcide:gradle-semantic-build-versioning:4.2.1'
    }
}

apply plugin: 'io.alcide.gradle-semantic-build-versioning'
*/
rootProject.name="ns4kafka"
include 'cli'
include 'api'

````
Project is available here : https://github.com/michelin/ns4kafka
