### ISSUE TITLE
The `reflect-config.json` file isn't generated if the `io.micronaut.application` plugin is applied

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-gradle-plugin#324]
### Expected Behavior

A Micronaut Data JPA application with GraalVM should work.

### Actual Behaviour

Micronaut Data JPA with GraalVM test applications have started to fail this morning. They worked last Friday.

When starting the application it fails with:

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.1-SNAPSHOT)

12:57:11.892 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
12:57:11.899 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
12:57:11.899 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.5.3.Final
12:57:11.901 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
12:57:11.902 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
12:57:11.903 [main] ERROR i.m.c.h.jpa.EntityManagerFactoryBean - Hibernate mapping error
org.hibernate.AnnotationException: No identifier specified for entity: example.domain.Pet
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:783)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactoryBuilder(EntityManagerFactoryBean.java:188)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2821)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2783)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1639)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2654)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1933)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3454)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:330)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at example.Application.main(Application.java:30)
12:57:11.903 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: example.domain.Pet
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.hibernate.SessionFactory] could not be loaded: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: example.domain.Pet
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1939)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3454)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:330)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:313)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at example.Application.main(Application.java:30)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.SessionFactory]

Message: No identifier specified for entity: example.domain.Pet
Path Taken: SessionFactory.hibernateSessionFactory([SessionFactoryBuilder sessionFactoryBuilder])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2364)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2821)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2783)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1639)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactory3$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3282)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3268)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2654)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1933)
	... 8 common frames omitted
Caused by: org.hibernate.AnnotationException: No identifier specified for entity: example.domain.Pet
	at org.hibernate.cfg.InheritanceState.determineDefaultAccessType(InheritanceState.java:266)
	at org.hibernate.cfg.InheritanceState.getElementsToProcess(InheritanceState.java:211)
	at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:783)
	at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:225)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:239)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:282)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:86)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:479)
	at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:85)
	at org.hibernate.boot.MetadataSources.buildMetadata(MetadataSources.java:202)
	at io.micronaut.configuration.hibernate.jpa.EntityManagerFactoryBean.hibernateSessionFactoryBuilder(EntityManagerFactoryBean.java:188)
	at io.micronaut.configuration.hibernate.jpa.$EntityManagerFactoryBean$HibernateSessionFactoryBuilder2$Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:136)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2337)
	... 22 common frames omitted
```

This happens with all databases except H2.

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal`
- `cd micronaut-data-jpa-graal`
- `git checkout error-graalvm`
- `sdk use java 21.3.0.r11-grl`
- `./gradlew nativeCompile`
- `docker run -it --rm -p 5432:5432 -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=pets postgres:11.5-alpine`
- `./build/native/nativeCompile/data-jpa-postgres`

### Environment Information

- Linux Mint 20.2
- GraalVM JDK 11 & 17

### Version

3.2.1-SNAPSHOT and Micronaut Data 3.2.1-SNAPSHOT

**Comment by ilopmar** [comment]
This happens because of the upgrade to use the new Micronaut Gradle plugin I did last Friday. This is the commit https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/commit/7c942ce88d309f3002a5b150e9b59243859e038a and reverting it make it work again.

@melix it seems like the some options in the `application.yml` file are not included in the native image. 

Something like this also happened in the "Management" GraalVM test application. When sending a request to the `/info` endpoint, the app returns 401. This can only happen if the `application.yml` is not being included, because I'm allowing anonymous access to all users https://github.com/micronaut-graal-tests/micronaut-management-graal/blob/3.2.x/src/main/resources/application.yml#L5-L9.

The real strange thing is that these are the only applications that have failed.

**Comment by ilopmar** [comment]
Confirmed that's the issue. See the following:

In `1` we start the app but the request returns `401`. Then, in `2` we set the `sensitivity` to false and start the app again. Now the  `curl` request returns 200 and the right data.

![image](https://user-images.githubusercontent.com/559192/143869114-9001e20e-7808-403b-a846-48a3a9df61d1.png)

**Comment by melix** [comment]
So this is really strange because this argument is passed:

> -H:ConfigurationFileDirectories=/tmp/micronaut-data-jpa-graal/build/native/generated/generateResourcesConfigFile

And the generated config file contains:

```
{
  "resources" : {
    "includes" : [ {
      "pattern" : "\\Qapplication.yml\\E"
    }, {
      "pattern" : "\\Qlogback.xml\\E"
    } ],
    "excludes" : [ ]
  },
  "bundles" : [ ]
}
```

Could there be another `application.yml` on classpath?

**Comment by graemerocher** [comment]
Are resources on the classpath?

**Comment by melix** [comment]
The jar of the app is on the native image classpath and definitely includes the config file.

**Comment by ilopmar** [comment]
> Could there be another `application.yml` on classpath?

There's only one `application.yml` file in the test app.

**Comment by melix** [comment]
So this isn't about `application.yml`: if I change the postgres port in the `application.yml` file I get a different error (connection refused) so it's definitely used.

**Comment by ilopmar** [comment]
This is the management app I took the screenshot from: https://github.com/micronaut-graal-tests/micronaut-management-graal
Checkout the branch `3.2.x` and build the native image to reproduce the error. Somehow the config in `application.yml` is not included because the `/info` endpoint doesn't work...

**Comment by graemerocher** [comment]
I think we need 2 issue reports as it is confusing that you started with one thing and now have mixed in other things.

The error in the first report seems to be that reflection metadata is missing for `example.domain.Pet`

This reflection metadata should be generated automatically if `micronaut-graal` annotation processor is on the annotation processor classpath. Previous versions of the plugin added this automatically if you were using GraalVM to build, but perhaps now because of the toolchain business this is no longer the case?

**Comment by melix** [comment]
> This reflection metadata should be generated automatically if micronaut-graal annotation processor is on the annotation processor classpath. Previous versions of the plugin added this automatically if you were using GraalVM to build, but perhaps now because of the toolchain business this is no longer the case?

mmm, this seems like a more serious candidate indeed.

**Comment by melix** [comment]
> we need 2 issue reports as it is confusing that you started with one thing and now have mixed in other things.

Correct, for the 2d one the generated resources config file indeed doesn't include the `application.yml` file for some reason. Which, in that case, would probably be a bug in the native plugin.

**Comment by ilopmar** [comment]
Ok, sorry for mixing up the two issues. I'll keep this one for the JPA issue and I'll file a new one for the `application.yml` in the Management app

**Comment by melix** [comment]
Alright for this issue the bug is that the annotation processor is only added to Micronaut _libraries_ (not application). So the workaround is to add the processor manually:

```
dependencies {
    annotationProcessor("io.micronaut.data:micronaut-data-processor")
    annotationProcessor("io.micronaut:micronaut-graal")
    ...
```
