### ISSUE TITLE
Upgrade gradle-docker-plugin to 7.1.0+

### ISSUE THREAD

**Issue by fhenskens** [micronaut-projects/micronaut-gradle-plugin#363]
### Feature description

gradle-docker-plugin v7.1.0 added in support for specifying the build platform.

I've updated this dependency to 7.2.0 in gradle/libs.versions.toml locally, which allowed me to set dockerBuild.platfom = "linux/amd64" fine, and got me back up and running.

Removing that line, it appears the new version of bmuschko's plugin adds in manifest files for the M1 chips (edit: I was wrong. dockerBuild.platform just stays present and set in the active gradle engine if removed from the build.gradle file).

Anyone who has bought or been assigned a dev pc running on apple silicon will appreciate this.

Unfortunately, the gradle-docker-plugin's newer versions are built on java 11, so it also requires the tooling to be upgraded from 8 to 11 in build.gradle

How do you guys feel about the change in base required java version?

**Comment by melix** [comment]
This will be doable once Micronaut 4 is out.

**Comment by fhenskens** [comment]
Wonderful, thank you very much!

**Comment by fhenskens** [comment]
If anyone else is having trouble with this, you can get around it checking out a copy, bumping the two version numbers, and using `--include-build "../micronaut-gradle-plugin" build`

**Comment by donbeave** [comment]
It will be nice to update to the latest `7.3.0` version, the current version doesn't work on Apple M1 devices. I'm getting this error:

```
> Task :tailrocks-marketplace-api-app:buildLayers UP-TO-DATE
Build cache key for task ':tailrocks-marketplace-api-app:buildLayers' is 8391c91386311f7fe4b8a1163c77b4e3
Skipping task ':tailrocks-marketplace-api-app:buildLayers' as it is up-to-date.
:tailrocks-marketplace-api-app:buildLayers (Thread[Execution worker for ':' Thread 6,5,main]) completed. Took 0.001 secs.
:tailrocks-marketplace-api-app:dockerBuild (Thread[Execution worker for ':' Thread 6,5,main]) started.
producer locations for task group 0 (Thread[Execution worker for ':',5,main]) started.
producer locations for task group 0 (Thread[Execution worker for ':',5,main]) completed. Took 0.0 secs.
Exception in thread "docker-java-stream--1595765382" java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.httpclient5.UnixDomainSocket
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

And I found it's fixed already here: https://github.com/bmuschko/gradle-docker-plugin/issues/1035

**Comment by eb-jorgemaroto** [comment]
any updates on this one? I'm facing the same issue

**Comment by donbeave** [comment]
As I understand this plugin will upgrade its Gradle Docker dependency with the release of a new major version specially for Micronaut 4.

**Comment by fhenskens** [comment]
Here is a workaround that gets things working on silicon chips
```
import static org.apache.tools.ant.taskdefs.condition.Os.*

ext.isSilicon = { ->
    if (isFamily(FAMILY_MAC)) {
        new ByteArrayOutputStream().withStream { os ->
            exec {
                executable = "sysctl"
                args = ["-n", "machdep.cpu.brand_string"]
                standardOutput = os
            }
            print("sysctl result: $os")
            return os.toString().contains("Apple M")
        }
    } else {
        return false;
    }
}

tasks.named("dockerfile") {
    if (isSilicon())
        baseImage = "arm64v8/openjdk:17-jdk"
}
```

**Comment by melix** [comment]
The docker plugin on `master` is on version 9+
