### ISSUE TITLE
AOT doesn't work

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-gradle-plugin#393]
### Expected Behavior

Everything should work

### Actual Behaviour

Now the building is proceeding correctly, the start of the service also works, but when trying to initialize the beans I see this exception (logs from ):
```
Java configurer loaded
16:28:37.873 INFO  [main] i.m.c.e.DefaultEnvironment [DefaultEnvironment.java:159] - Established active environments: [local]
16:28:37.878 INFO  [main] c.m.b.c.MyEntityProperties [MyEntityProperties.java:19] - prop = null
16:28:37.879 ERROR [main] i.m.runtime.Micronaut [Micronaut.java:328] - Error starting Micronaut server: Bean definition [com.micronaut.bug.controller.MyEntityController] could not be loaded: Error instantiating bean of type  [com.micronaut.bug.controller.MyEntityController]

Message: No backing RepositoryOperations configured for repository. Check your configuration and try again
Path Taken: new MyEntityController([MyEntityService entityService])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [com.micronaut.bug.controller.MyEntityController] could not be loaded: Error instantiating bean of type  [com.micronaut.bug.controller.MyEntityController]

Message: No backing RepositoryOperations configured for repository. Check your configuration and try again
Path Taken: new MyEntityController([MyEntityService entityService])
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1938)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:237)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3453)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3883)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:329)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
        at com.micronaut.bug.Application.main(Application.java:24)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.micronaut.bug.controller.MyEntityController]

Message: No backing RepositoryOperations configured for repository. Check your configuration and try again
Path Taken: new MyEntityController([MyEntityService entityService])
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2363)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:3267)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2820)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2782)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1638)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:1933)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1189)
        at com.micronaut.bug.controller.$MyEntityController$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:3281)
        at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2664)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1932)
        ... 7 common frames omitted
Caused by: io.micronaut.context.exceptions.ConfigurationException: No backing RepositoryOperations configured for repository. Check your configuration and try again
        at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:167)
        at io.micronaut.data.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:86)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
        at com.micronaut.bug.dao.MyEntityDao$Intercepted.save(Unknown Source)
        at com.micronaut.bug.service.MyEntityService.save(MyEntityService.java:37)
        at com.micronaut.bug.service.MyEntityService.init(MyEntityService.java:27)
        at com.micronaut.bug.service.$MyEntityService$Definition.initialize(Unknown Source)
        at com.micronaut.bug.service.$MyEntityService$Definition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2336)
        ... 19 common frames omitted
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.data.jdbc.operations.JdbcRepositoryOperations] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2795)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:888)
        at io.micronaut.data.intercept.DataIntroductionAdvice.findInterceptor(DataIntroductionAdvice.java:164)
        ... 29 common frames omitted
```

### Steps To Reproduce

Just run `gradle clean nativeOptimizedCompile -i` for example application and try to run the service. I confiured this service with `.eagerInitSingletons(true)` So that you can reproduce the problem immediately at the start of the service. This service works perfectly without AOT.

### Environment Information

- Windows 10
- GraalVM 22.0.0.2
- JDK 17

### Example Application

https://github.com/altro3/micronaut3-bug

### Version

3.3.4

**Comment by melix** [comment]
Thanks for the reproducer. This is expected. If you want to use Micronaut AOT, then you _must_ use the alternate context configuration mechanism, which is to use `ContextConfigurer`. Your `Application.java` class should look like this instead:

```java
package com.micronaut.bug;

import io.micronaut.context.ApplicationContextBuilder;
import io.micronaut.context.ApplicationContextConfigurer;
import io.micronaut.context.annotation.ContextConfigurer;
import io.micronaut.runtime.Micronaut;

@ContextConfigurer
public class Application implements ApplicationContextConfigurer {

    @Override
    public void configure(ApplicationContextBuilder builder) {
        builder.deduceEnvironment(false)
           .banner(false)
           .eagerInitSingletons(true)
           .defaultEnvironments("local");
    }

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }

}
```

Please note, however, that it's likely not what you want for production: you'll want your regular environment to be used in the AOT optimized application. Basically the fact that you are using `defaultEnvironments("local")` interferes with the execution of the AOT optimized application, which assumes a particular deployment environment. In particular, you should do:

```gradle
micronaut {
    ...
   aot {
        version = "1.0.0-M7"
        cacheEnvironment = true
        optimizeServiceLoading = true
        optimizeClassLoading = true
        convertYamlToJava = true
        precomputeOperations = true
        deduceEnvironment = false
         // force AOT to start its analysis using the runtime deployment environment, not "local"
        targetEnvironments = ["default"] 
    }
}
```

Now the problem is that the optimized application still has `defaultEnvironments("local")`, so while the analysis is performed with the "application" (default) environment, when the AOT application is started, it will use this `local` + `default`.

I am not quite sure why this isn't working right now, I'll keep you posted. But I'm also moving this issue to Micronaut AOT as there's a deeper problem to solve.
