### ISSUE TITLE
Docker Plugin does not work on M1 Mac

### ISSUE THREAD

**Issue by darylrobbins** [micronaut-projects/micronaut-gradle-plugin#520]
When attempting to complete a Docker Build on my M1 Mac, I receive the following error:
```
> Task :api:dockerfile UP-TO-DATE
Exception in thread "docker-java-stream-1969837327" java.lang.UnsatisfiedLinkError: Can't load library: /Users/daryl/Library/Caches/JetBrains/IntelliJIdea2022.2/tmp/jna10213887299513046605.tmp
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.github.dockerjava.httpclient5.UnixDomainSocket.<clinit>(UnixDomainSocket.java:80)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl$2.createSocket(ApacheDockerHttpClientImpl.java:116)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:125)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:409)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:164)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:174)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:135)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
	at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
	at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
	at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I can confirm this issue is specifically caused by the version of the Docker Gradle plugin being used (6.7.0). I tried including this version of the Docker Gradle plugin directly in a plain vanilla (non-micronaut project) and received the same error. Upon upgrading the Docker Gradle plugin to the latest version (7.4.0), everything worked perfectly.

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/f3687ae6b2d8d830b7742788577b80351fa88ffc/gradle/libs.versions.toml#L3

**Comment by dmeibusch** [comment]
My team hasn't had an issue on M1 Macs when using Docker Desktop, however it has started occurring now that some of us have switched to Rancher (with dockerd).

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by alvarosanchez** [comment]
Thanks for the report. QA intake checked the current repository state and the linked PR history, and this issue is already implemented on supported plugin lines.

The original report identified `com.bmuschko:gradle-docker-plugin` `6.7.0` as the failing dependency and noted that upgrading fixed the problem. In this repository, that dependency was upgraded by PR `#514` (`fix(deps): update dependency com.bmuschko:gradle-docker-plugin to v8`), which merged on September 12, 2022. The contributor PR linked from this issue, `#521`, was then closed the same day as superseded by `#514`.

That fix shipped in released builds starting with `v4.0.0-M2` on May 5, 2023. As of April 24, 2026, the latest stable Micronaut Gradle Plugin release is `v4.6.2`, and it uses Docker Gradle plugin `9.4.0`. The current default branch `master` is on `5.0.0-SNAPSHOT` and uses Docker Gradle plugin `10.0.0`.

A maintainer also asked on May 26, 2025 whether this still reproduced on the latest version, and there was no follow-up with a current reproduction. Given the shipped dependency upgrade and the lack of a supported-version reproducer, QA is closing this as already implemented.

If you can still reproduce the same failure on `v4.6.2` or newer, please open a new issue with the exact failing task, full `--stacktrace` output, your macOS Docker runtime (`Docker Desktop`, `Colima`, `Rancher Desktop`, `OrbStack`, etc.), and `docker version` output.
---
###### ✨ This message was AI-generated using gpt-5.4
