### ISSUE TITLE
Unable to create Docker Image of non-micronaut module

### ISSUE THREAD

**Issue by maccuaa** [micronaut-projects/micronaut-gradle-plugin#627]
### Expected Behavior

The dockerBuild task should read a Dockerfile in a Gradle module and create a Docker image.

My Gradle project includes backend Micronaut services which build fine. The problem comes when trying to build a UI service which is not based on Micronaut.

### Actual Behaviour

The build fails with the following error:

```
$ ../gradlew dockerBuild
Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Cannot locate specified Dockerfile: /Users/maccuaa/Projects/eas/ui/Dockerfile"}

        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
```

The Dockerfile path listed in the error message does in fact exist.

### Steps To Reproduce

build.gradle:

```groovy
plugins {
  alias(libs.plugins.node)
  alias(libs.plugins.micronaut.docker)
  alias(libs.plugins.micronaut.application)
}


dockerBuild {
  images = ["eas/ui"]
}

```

libs.versions.toml
```
[versions]
micronaut-gradle = "3.6.2"

[plugins]
micronaut-application    = { id = "io.micronaut.application", version.ref = "micronaut-gradle" }
micronaut-docker         = { id = "io.micronaut.docker", version.ref = "micronaut-gradle" }
node                     = "com.github.node-gradle.node:3.4.0"
```

Ideally I wouldn't have to apply the micronaut application plugin. If I omit it then the build fails with the following error:

```
../gradlew dockerBuild

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':ui:buildLayers'.
> Could not create task ':ui:runnerJar'.
   > Extension of type 'JavaApplication' does not exist. Currently registered extension types: [ExtraPropertiesExtension, BasePluginExtension, DefaultArtifactPublicationSet, SourceSetContainer, ReportingExtension, JavaToolchainService, JavaPluginExtension, TestingExtension, SpotlessExtension, JacocoPluginExtension, LibrariesForLibs, VersionCatalogsExtension, NodeExtension, PackageJsonExtension, MicronautExtension, DockerExtension]
```

Alternatively, I could leverage the bmuschko/gradle-docker-plugin tasks directly since that's what this plugin is based on however I haven't been able to get that working either.

### Version

3.7.1

**Comment by maccuaa** [comment]
Closing. Managed to get it working by setting the `inputDir` as described here https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/214#issuecomment-902879502

To get it working properly I had to define a `.dockerignore` file to ignore the `node_modules` folder and any other folder that had a large number of files.
