### ISSUE TITLE
AOT and Test Resources

### ISSUE THREAD

**Issue by n0tl3ss** [micronaut-projects/micronaut-gradle-plugin#795]
### Expected Behavior

In multimodule project when there is stale test resources configuration in`~/.micronaut` folder, aot optimisation fails with:

```
Caused by: io.micronaut.testresources.client.TestResourcesException: java.net.ConnectException
        at io.micronaut.testresources.client.DefaultTestResourcesClient.request(DefaultTestResourcesClient.java:144)
        at io.micronaut.testresources.client.DefaultTestResourcesClient.getRequiredPropertyEntries(DefaultTestResourcesClient.java:99)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.micronaut.testresources.client.TestResourcesClientPropertySourceLoader$ClientTestResourcesResolver.getPropertyEntries(TestResourcesClientPropertySourceLoader.java:50)
        at io.micronaut.testresources.core.LazyTestResourcesPropertySourceLoader$LazyPropertySource.computeKeys(LazyTestResourcesPropertySourceLoader.java:98)
        at io.micronaut.testresources.core.LazyTestResourcesPropertySourceLoader$LazyPropertySource.iterator(LazyTestResourcesPropertySourceLoader.java:90)
        at io.micronaut.context.env.PropertySourcePropertyResolver.processPropertySource(PropertySourcePropertyResolver.java:596)
        at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:449)
        at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:278)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:881)
        at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:850)
        at io.micronaut.aot.core.context.ApplicationContextAnalyzer.finalizeConfiguration(ApplicationContextAnalyzer.java:114)
        at io.micronaut.aot.core.context.ApplicationContextAnalyzer.create(ApplicationContextAnalyzer.java:91)
        at io.micronaut.aot.MicronautAotOptimizer$Runner.execute(MicronautAotOptimizer.java:328)
        at io.micronaut.aot.MicronautAotOptimizer.execute(MicronautAotOptimizer.java:202)
        ... 16 more
````

### Actual Behaviour

Gradle task should finish succesfully.

### Steps To Reproduce

1. Create test-resources stale configuration files in `~/.micronaut`.
2. Run `./gradlew assemble`.
3. Observe error.

### Environment Information

- OS: 22.4.0 Darwin Kernel Version 22.4.0 (ARM)
- JDK: `openjdk 17.0.6 2023-01-17`

### Version

4.0.2

**Comment by melix** [comment]
Educated guess would be that the AOT system properties are not passed to the AOT optimizer run task.

**Comment by dgrumieaux** [comment]
+1 see this with Maven in a multi module build as well.

**Comment by alvarosanchez** [comment]
Thanks for the report. QA intake reviewed this against the current `micronaut-gradle-plugin` repository and the original failure path is already fixed here.

Evidence:
- The same AOT/test-resources `TestResourcesException: java.net.ConnectException` failure was later tracked in #852 and fixed by PR #853 (`Fix test resources client on optimizer classpath`), merged on October 20, 2023.
- That fix is present in released versions starting with `v4.1.2`.
- Current `master` still carries regression coverage in `functional-tests/src/test/groovy/io/micronaut/gradle/testresources/TestResourcesWithAotSpec.groovy`, and QA reran `./gradlew functional-tests:test --tests 'io.micronaut.gradle.testresources.TestResourcesWithAotSpec'` successfully on April 20, 2026.

Given that evidence, there is no remaining Gradle-plugin implementation work on this issue. If you can still reproduce a related failure on a current release, please open a new issue with the exact Micronaut Gradle plugin version, whether the failure is Gradle or Maven, and a minimal reproducer.

Closing as already implemented.

---
###### ✨ This message was AI-generated using gpt-5.4
