### ISSUE TITLE
Index out of bounds if main class is not in a package

### ISSUE THREAD

**Issue by axel22** [micronaut-projects/micronaut-gradle-plugin#803]
### Expected Behavior

No index out of bounds exception.

### Actual Behaviour

Index out of bounds exception.

### Steps To Reproduce

Write any Gradle project with the Micronaut plugin in which the main class is not in a package.

Example:

```
plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.0.2"
    id("io.micronaut.aot") version "4.0.2"
}

version = "0.1"
group = "simple.niohttp.app"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut:micronaut-http-server-netty")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut:micronaut-http-client")
}

application {
    mainClass.set("NioHttpServer")
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
    targetCompatibility = JavaVersion.toVersion("17")
}

graalvmNative.toolchainDetection.set(false)
micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        enableNativeImage.set(true)
        optimizeServiceLoading.set(true)
        convertYamlToJava.set(false)
        precomputeOperations.set(true)
        cacheEnvironment.set(true)
        optimizeClassLoading.set(true)
        deduceEnvironment.set(true)
        optimizeNetty.set(true)
    }
}
graalvmNative {
    binaries["optimized"].buildArgs.add("-H:+UseDeprecatedOldClassInitialization")
}
```

Error:

```
Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, -1) out of bounds for length 13
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
        at io.micronaut.gradle.aot.MicronautAotPlugin.lambda$configureAotDefaults$1(MicronautAotPlugin.java:140)
```

This line needs to be fixed:

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/aot-plugin/src/main/java/io/micronaut/gradle/aot/MicronautAotPlugin.java#L140

### Version

4.0.3

**Comment by sdelamo** [comment]
why do you want to have a main class not in a package?

**Comment by axel22** [comment]
(i.e. I fixed it in the source I was working with, but I opened this issue FYI, in case you want to output an error message in this case)
