### ISSUE TITLE
Setting dockerfile baseImage changes function-app main class to default MicronautLambdaRuntime

### ISSUE THREAD

**Issue by miguelaferreira** [micronaut-projects/micronaut-gradle-plugin#820]
### Expected Behavior

Changing the base image used for building docker containers should not affect the defined main class for the application.

### Actual Behaviour

Setting a base image for the `dockerfile` task, when the runtime is `lambda_provided`, changes the main class defined in the manifest of the built JARs to `io.micronaut.function.aws.runtime.MicronautLambdaRuntime`.

### Steps To Reproduce

1. Create an application (in the example a function application)
   ```
   mn create-function-app  -f aws-lambda-custom-runtime,aws-lambda test-function-app
   cd test-function-app
   ```
2. Change `build.gradle` to set `lambda_provided` runtime and a different docker container base image
   ```diff
   35c35
   <     runtime("lambda_provided")
   ---
   >     runtime("lambda_java")
   43,47c43,44
   < tasks {
   <     dockerfile {
   <         baseImage = 'eclipse-temurin:17-jre'
   <     }
   < }
   ```
3. Build a docker image for the app
   ```
   ./gradlew dockerBuild
   cat build/tmp/runnerJar/MANIFEST.MF | grep "Main-Class"
   ```
   The main class is `io.micronaut.function.aws.runtime.MicronautLambdaRuntime`

### Environment Information

- Operating System: macOS 13.5.1 (22G90)
- JDK Version:
  ```
  openjdk version "17.0.8" 2023-07-18
  OpenJDK Runtime Environment GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15)
  OpenJDK 64-Bit Server VM GraalVM CE 17.0.8+7.1 (build 17.0.8+7-jvmci-23.0-b15, mixed mode, sharing)
   ```
- Chip: Apple M2 Max 👈 This chip is the reason why I needed to change the docker container base image, since the default one does not have an arm64 build

### Version

4.1.0

**Comment by sdelamo** [comment]
@miguelaferreira `lambda-provided` is a runtime thought when you deploy to AWS Lambda custom runtime. We need the main class to be the entry point of the Native Image which does the Lambda runtime API polling. 

If you want to deploy a JAR file to a AWS Lambda Java runtime, you should use `lambda_java` runtime instead.

**Comment by miguelaferreira** [comment]
@sdelamo Thanks for getting back to me. I don't want to deploy a jar, I want to deploy as a container image. Specifying `lambda_provided` sets the main class tot he default micronaut implementation, and then I can't build my container image using the docker gradle tasks.

**Comment by sdelamo** [comment]
we don't have any runtime tailored to deploy as a container image. why do you want to do that instead of native executable to custom runtime or java runtime?

**Comment by miguelaferreira** [comment]
Isn't the custom runtime deployed as a container as well? I've always assumed custom runtime is deployed as a container. 

Next to that, the MicronautLambdaRuntime class seems wired for API Gateway, and my lambda function isn't integrated with that. Therefore I want to implement my own class and have that wired as the main class of my application.

**Comment by miguelaferreira** [comment]
It seems that all lambdas I run face this problem now after upgrading to Micronaut 4. For one I was running Micronaut `4.0.0-RC5` with the gradle plugin version `4.0.0-M8`. After upgrading to Micronaut 4.3.1 and gradle plugin version 4.0.4, the lambda stops working due to the manipulation of the main class. 

As I mentioned before, not all lambdas are integrated with ApiGateway, in my case they are triggered directly form S3 events. I now get errors like this:
```
Invocation with requestId [6b81b933-0322-460a-b7af-9f6e1af61eca] failed: Cannot invoke "String.length()" because "this.input" is null 
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
at java.base/java.net.URI$Parser.parse(Unknown Source)
at java.base/java.net.URI.<init>(Unknown Source)
at java.base/java.net.URI.create(Unknown Source)
at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyServletRequest.<init>(ApiGatewayProxyServletRequest.java:59)
...
```

The workaround I've used in other functions is to not use gradle to build the docker containers used to deploy the function. That means I have to create and maintain my own Dockerfile and scripts around it, for example like [this](https://github.com/miguelaferreira/ses-notification-lambda/pull/6/commits/56b26c32b56360d7799323f239e645026f1320f5).

Imposing an implementation for the main class of any lambda function seems overly restrictive from Micronaut.

**Comment by miguelaferreira** [comment]
I was reading the [Micronaut docs](https://micronaut-projects.github.io/micronaut-aws/latest/guide/#customRuntimes) again to make sure I didn't miss anything. Please correct me if I'm wrong, but what I understand from it is that we should be able to use custom runtimes and still define our own main class.

> Micronaut’s dependency [micronaut-function-aws-custom-runtime](https://mvnrepository.com/artifact/io.micronaut.aws/micronaut-function-aws-custom-runtime) eases the creation of AWS Lambda Custom runtime to execute a Micronaut function.
>
> The main API you will interact with is [AbstractMicronautLambdaRuntime](https://micronaut-projects.github.io/micronaut-aws/latest/api/io/micronaut/function/aws/runtime/AbstractMicronautLambdaRuntime.html). An abstract class which you can extend to create your custom runtime mainClass. That class includes the necessary code to perform the [Processing Tasks](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html#runtimes-custom-build) described in the Custom Runtime documentation.

Then it goes on saying that Microanut ships 3 already implemented main classes for functions that respond to HTTP triggers.
