### ISSUE TITLE
Issue with ./gradlew nativeImage and data jdbc for native  images

### ISSUE THREAD

**Issue by knoma** [micronaut-projects/micronaut-gradle-plugin#88]
There seems to be an issue using the ``` ./gradlew nativeImage```  to create a native image with 2.1.4, jdk11 and graalvm 20.3  
for a jdbc app.

```
The native  command works 
➜  jdbc_mirco git:(main) ✗ native-image --no-fallback --class-path build/libs/jdbc_mirco-*-all.jar
[data-jdbc-h2:31924]    classlist:   1,531.65 ms,  0.94 GB
[data-jdbc-h2:31924]        (cap):   3,966.99 ms,  0.94 GB
[data-jdbc-h2:31924]        setup:   4,999.03 ms,  0.94 GB
[data-jdbc-h2:31924]     (clinit):   1,108.58 ms,  4.33 GB
[data-jdbc-h2:31924]   (typeflow):  19,085.36 ms,  4.33 GB
[data-jdbc-h2:31924]    (objects):  33,740.15 ms,  4.33 GB
[data-jdbc-h2:31924]   (features):   2,938.34 ms,  4.33 GB
[data-jdbc-h2:31924]     analysis:  60,342.66 ms,  4.33 GB
[data-jdbc-h2:31924]     universe:   1,883.11 ms,  4.33 GB
[data-jdbc-h2:31924]      (parse):   3,164.06 ms,  4.46 GB
[data-jdbc-h2:31924]     (inline):   5,847.98 ms,  6.48 GB
[data-jdbc-h2:31924]    (compile):  23,975.84 ms,  7.67 GB
[data-jdbc-h2:31924]      compile:  36,239.00 ms,  7.67 GB
[data-jdbc-h2:31924]        image:   5,955.65 ms,  7.69 GB
[data-jdbc-h2:31924]        write:   1,328.11 ms,  7.69 GB
[data-jdbc-h2:31924]      [total]: 112,450.91 ms,  7.69 GB
```

the task fails, I tried    "io.micronaut.application" version 1.0.5 and  1.2.0
```
➜  jdbc_mirco git:(main) ✗ ./gradlew nativeImage

> Task :nativeImage
[micronaut-graalvm-app:32024]    classlist:   1,508.32 ms,  0.96 GB
[micronaut-graalvm-app:32024]        (cap):   3,857.28 ms,  0.96 GB
[micronaut-graalvm-app:32024]        setup:   4,873.12 ms,  0.96 GB
[micronaut-graalvm-app:32024]     (clinit):   1,155.05 ms,  5.63 GB
[micronaut-graalvm-app:32024]   (typeflow):  15,022.93 ms,  5.63 GB
[micronaut-graalvm-app:32024]    (objects):  19,724.85 ms,  5.63 GB
[micronaut-graalvm-app:32024]   (features):   4,414.42 ms,  5.63 GB
[micronaut-graalvm-app:32024]     analysis:  44,340.34 ms,  5.63 GB
Error: Unsupported features in 9 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
Trace:
        at parsing org.h2.util.Bits.readDouble(Bits.java:184)
Call path from entry point to org.h2.util.Bits.readDouble(byte[], int):
        at org.h2.util.Bits.readDouble(Bits.java:184)
        at org.h2.util.geometry.EWKBUtils$EWKBSource.readCoordinate(EWKBUtils.java:217)
        at org.h2.util.geometry.EWKBUtils.addCoordinate(EWKBUtils.java:475)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:376)
        at org.h2.util.geometry.EWKBUtils.parseEWKB(EWKBUtils.java:292)
        at org.h2.value.ValueGeometry.getEnvelopeNoCopy(ValueGeometry.java:238)
        at org.h2.mvstore.db.MVSpatialIndex$FindBoundsCursor.check(MVSpatialIndex.java:474)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.fetchNext(MVRTreeMap.java:527)
        at org.h2.mvstore.rtree.MVRTreeMap$RTreeCursor.hasNext(MVRTreeMap.java:484)
        at javax.security.auth.Subject.hashCode(Subject.java:928)
        at java.util.HashMap.hash(HashMap.java:339)
        at java.util.HashMap.get(HashMap.java:552)
        at com.oracle.svm.jni.access.JNIReflectionDictionary.getLinkage(JNIReflectionDictionary.java:146)
        at com.oracle.svm.jni.functions.JNIFunctions.RegisterNatives(JNIFunctions.java:349)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_RegisterNatives_7728ce15b57af339792ad95c60f247990e0df65e(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: VarHandle object must be a compile time constant
```

Steps to reproduce 

Create a new project via `mn create-app knoma.web.jdbc_micro --features data-jdbc,http-client,graalvm --jdk=11`

Bumped up io.micronaut.application to 1.2.0 and create controller via `mn create-controller Person`
Next I created the `native-image.properties `with `Args = --verbose --report-unsupported-elements-at-runtime`

I also tried 
```
nativeImage {
    args('--report-unsupported-elements-at-runtime')
    imageName('micronaut-graalvm-app')
}
```

./gradlew nativeImage still fails 
but` native-image --no-fallback --class-path build/libs/...` works after adding the other properties like name and class.

**Comment by ilopmar** [comment]
@knoma which GraalVM version are you using, Java 8 or Java 11?

**Comment by knoma** [comment]
I'm using graalvm64-11.0.9 (20.3)

**Comment by knoma** [comment]
I also tried to add` id "io.micronaut.application" version '1.2.0'` to https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/2.2.x_h2 and to run the ` ./gradlew nativeImage` and I got the same failure.

**Comment by ilopmar** [comment]
Can you please give it a try with `./gradlew nativeImage` and Java 8? I'm asking because I've seen issues like the one you posted with Java 11 so I want to make sure if this is one of those.

**Comment by knoma** [comment]
I tried the Gradle native image task with jdk8 and graalvm 20.2 see Gitter thread and it worked. I had the hope that jdk11 will work with graalvm

**Comment by knoma** [comment]
Just tried [micronaut-data-jdbc-graal](https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/tree/2.2.x_h2) and `"io.micronaut.application" version '1.2.0'` with `./gradlew nativeImage` by using `graalvm-ce-java8-20.3.0` which worked. I was able to compile a native image and run it.

**Comment by knoma** [comment]
I tried this today with graalvm-ce-java11   21.1.0 and micronaut 2.5 and it worked with a new jdk11 project

```
➜  bigdata-user-signals-kafkaten git:(main) cd ..
➜  Project cd micronaut/jdbc-micro
➜  jdbc-micro ./gradlew nativeImage
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 6s
3 actionable tasks: 3 up-to-date
```

I will close this
